### ISSUE TITLE
snewpy.get_models() fails if installing not from PyPI

### ISSUE THREAD

**Issue by Sheshuk** [SNEWS2/snewpy#124]
Hi!
I'm unable to get the models, when installing snewpy from git:
```bash
> pip install "git+https://github.com/SNEWS2/snewpy.git"
```
and then 
```bash
> python -c 'import snewpy; snewpy.get_models()'
```
i get:
```
Available models in this version of SNEWPY: []

Type a model name, 'all' to download all models or <Enter> to cancel: all

You have selected the models: dict_keys([])
```

The same happens if snewpy is installed locally with 
```bash
> git clone git@github.com:SNEWS2/snewpy.git
> pip install .
```
Probably this is expected behavior, as in the latter case all the models are present in `models/`, but the function output looks misleading, some warning message would be useful.

**Comment by JostMigenda** [comment]
That is indeed expected behaviour. When publishing SNEWPY to PyPI, there is [a separate step](https://github.com/SNEWS2/snewpy/blob/main/.github/workflows/publish.yml#L30) that generates the list of model URLs _for that specific release_. This is to ensure that `snewpy.get_models()` only offers models supported by that version, and no older models that were removed or newer models that don’t work with the currently installed version.

As you say, anyone cloning the whole repo will already have all models downloaded.

pip installing from git is not something I’d recommend:
For one, it effectively is equivalent to
```
git clone git@github.com:SNEWS2/snewpy.git /tmp/snewpy/
pip install /tmp/snewpy/
rm -r /tmp/snewpy/
```
so you’re downloading all the models anyway (and just discarding them immediately after the install).
Also, we don’t guarantee that the repo will be in a consistent state after any arbitrary commit that you may install that way (e.g. we may have already merged new model files, but the code to support that model may not be ready yet), so generating a list of available models for an arbitrary commit may lead to confusion.
Is there any good use case for pip installing from git that I’m missing?

So I don’t think there’s a good way to fix this; but I can certainly add a warning message.

**Comment by Sheshuk** [comment]
>  Is there any good use case for pip installing from git that I’m missing?
It's sometimes useful when need to test a specific branch or tag.
For example, if I have a package depending on snewpy I can put this into `requirements.txt`:
```
git+https://github.com/SNEWS2/snewpy.git@development
```
and test how it works with the `development` version.

Off course in snewpy case it automatically checks out all the models with it, so probably it's not very feasible.
