### ISSUE TITLE
Get SNOwGLoBES to run in low energy with smaller bins

### ISSUE THREAD

**Issue by Sheshuk** [SNEWS2/snewpy#141]

**Comment by Sheshuk** [comment]
Hi @joesmolsky, can you describe here, what changes are needed in the snowglobes configuration to do that? 
And also, does a different binning mean we have to rebin the interaction crossections, detector efficiencies and smearing?

**Comment by Sheshuk** [comment]
I made the template to create the configuration file. Probably we'll need to change these lines: https://github.com/SNEWS2/snewpy/blob/af1b0d009a581f6b9f1fbf7d210de6a114d8bd09/python/snewpy/templates/supernova.glb#L16-L25

**Comment by JostMigenda** [comment]
A custom energy binning for low energy neutrinos is also one of the major updates currently planned for SNOwGLoBES ([see PR here](https://github.com/SNOwGLoBES/snowglobes/pull/15)). How is this issue related to that? Would it require that upcoming SNOwGLoBES version?

**Comment by joesmolsky** [comment]
Perhaps it is not strictly needed.  The preSN models all have maximum energies of 25 MeV or less.  Does it make since to use smaller energy bins than for SN models?

I am also thinking smaller energy bins will be useful for something like neutrino-proton elastic scattering.  This isn't included in SNOwGLoBES yet, but hopefully it will be in the near future.  

I think SNOwGLoBES 1.3 does look like a better version for the preSN models.  I was not up-to-date on the progress.

**Comment by joesmolsky** [comment]
In order to do non-standard energy bins with SNOwGLoBES 1.2, the binning needs to be defined at the top of each material's channels file.  There then also needs to be corresponding cross-section, smearing, and efficiency files for each channel.  This is how it was done for some high energy binning using news 1.2, but it looks like things are different with v1.3.

I am not yet sure about the non-standard binning in the neutrino fluxes.  Typically in SNOwGLoBES, the flux ranges from 0.0001 - 0.1001 GeV in 0.2 MeV increments, in GLoBES format.

**Comment by joesmolsky** [comment]
Implemented in https://github.com/joesmolsky/snowglobes/commit/da490424f9e23e5e02ccc6d97d7419e4e1f2f218
