### ISSUE TITLE
Problem downloading SN models: Warren a1.25 m120

### ISSUE THREAD

**Issue by PeterDenton** [SNEWS2/snewpy#145]
When executing "python -c 'import snewpy; snewpy.get_models()'" many SN models download, but one fails:

Failed to download https://github.com/SNEWS2/snewpy/raw/v1.1b4/models/Warren_2020/stir_a1.25/stir_multimessenger_a1.25_m120.h5 to 'SNEWPY_models/Warren_2020/stir_a1.25/stir_multimessenger_a1.25_m120.h5'.

at the end it says:

ERROR: 1 exceptions occured. ([<HTTPError 502: 'Bad Gateway'>])

When I rerun it, it works fine and the 120M Warren model file is downloaded. Maybe it is hitting the server too fast? This isn't that important of an issue. Maybe you could add a comment if such this 502 error pops up that rerunning might help. Also, some files weren't attempted to download on the first pass and were only downloaded on the second pass.

**Comment by JostMigenda** [comment]
We’re intentionally limiting downloads to at most 8 files in parallel and any server-side rate limiting should return a 429 error (not 502) so I don’t think it’s related to that. I can’t reproduce it and since it worked for you on the 2nd try as well, it may have just been a blip in one of GitHub’s servers.

Good point about adding a comment though; I’ll do that.

> Also, some files weren't attempted to download on the first pass and were only downloaded on the second pass.

Hm … that should usually not happen.
`get_models()` will generally skip downloads if files are already present on disk; the only exception being the README files for each model directory which will always re-download. (That’s because we may add more progenitors to a model later—and update the README accordingly—whereas we don’t want to modify existing model files since the risk of confusion would be too great.)

So if it’s only the README files that were downloaded in the 2nd pass, that is intended. (Though they should still have been downloaded in the 1st pass—can you please check?) If it’s any other files, please let me know which specific ones so I can debug this.

**Comment by PeterDenton** [comment]
Ah, it was just the readme files which were redownloaded and I see now that they were downloaded fine the first time, it's just a lot of lines and they all appeared at the end the second time.
