### ISSUE TITLE
Integration test fails under Python 3.7

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#155]
As noted in #154, the integration test currently [fails under Python 3.7](https://github.com/SNEWS2/snewpy/runs/4327623529?check_suite_focus=true). The error is in `sng.run()`, which has led me to chase down an asyncio rabbit hole …

The initial problem was that `asyncio.create_subprocess_exec()` doesn’t accept `pathlib.Path` arguments. This appears to have [changed in Python 3.8](https://bugs.python.org/issue35246), though [the documentation isn’t updated](https://docs.python.org/3.11/library/asyncio-eventloop.html#asyncio.loop.subprocess_exec) so maybe we shouldn’t rely on that. Luckily, that one’s an easy fix; draft PR coming soon.

Unfortunately, once that’s resolved I run into another error: `sng.run()` returns `RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')`
@Sheshuk, you appear to understand the guts of asyncio much better than I do—can you take a look at that?

**Comment by Sheshuk** [comment]
Investigating: looks like there's a problem with `asyncio.create_subprocess` when run in a separate thread (as I do in `snowglobes_interface`). Found the discussion [here](https://stackoverflow.com/questions/57629155/asyncio-function-works-when-called-from-script-but-not-from-flask-route).
The [ThreadedChildWatcher](https://docs.python.org/3/library/asyncio-subprocess.html#subprocess-and-threads) which lifted the restriction, was added only in python v3.8.
A possible solution would be to use thread pool workers for each flux file, instead of using async coroutines.
