### ISSUE TITLE
Provide output suitable for GEANT4

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#22]
We should have the neutrino interaction products generated in SNEWPY+SNOwGLoBES available for injection into a GEANT4 detector simulation. This requires (approximately) the following changes:

1. Factorize the interaction and detector response matrices in SNOwGLoBES (or identify where this is done inside the SNOwGLoBES code).
2. Change the SNOwGLoBES interface to allow the user to separately specify the interaction and response matrices or add a flag that has SNOwGLoBES only apply the interaction matrix when called.
3. Provide an interface to this function or flag in `run_snowglobes`.

**Comment by JostMigenda** [comment]
I think we need to discuss whether it makes sense to include this in SNEWPY+SNOwGLoBES, given that sntools exists and was designed from the start as an event generator that generates inputs for a GEANT4-based detector simulation. (Including things like event-level correlations between energy and direction of outgoing particles, which SNOwGLoBES can’t do by design.)

To me, it makes a lot of sense to use SNOwGLoBES as a versatile tool for very fast, approximate studies and then switch to sntools when you need precise, event-level information & want to employ a full detector simulation and reconstruction toolchain. And SNEWPY can be an essential tool in both cases—either as a front-end for SNOwGLoBES, or as a library [that makes sntools much more versatile](https://github.com/JostMigenda/sntools/issues/28) by enabling support for more models and flux transformations.

Right now, I think the main advantage of adding GEANT4 output to SNEWPY+SNOwGLoBES is that SNOwGLoBES support more detector types than sntools. So, if there’s interest in GEANT4 output for any detector types other than water Cherenkov, LS and WbLS (which sntools currently supports), then maybe we should first consider whether it’s easier to change SNOwGLoBES as described or to add the new detector type to sntools?

**Comment by e-mccarthy** [comment]
@JostMigenda  Others may feel differently, but I am personally in favor of releasing SNOwGLoBES v. 1.3 without a GEANT4 integration. We're a few user manual revisions away from pushing to public; adding a GEANT4 integration could easily add another year to that timeline (or be a v. 1.4 all by itself). I can definitely see needing that full reconstruction capability, but I agree with you that SNOwGLoBES is not the tool for it.

**Comment by schol** [comment]
Dear all,
Without having had a chance to look in detail at Jost’s proposed mods, I’m inclined to agree with Elise that G4 integration would be an increment beyond the upcoming release.

Might be good to discuss this at an upcoming meeting, if there is a chance.

Kate

From: e-mccarthy ***@***.***>
Date: Thursday, July 15, 2021 at 3:03 PM
To: SNEWS2/snewpy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SNEWS2/snewpy] Provide output suitable for GEANT4 (#22)

@JostMigenda<https://urldefense.com/v3/__https:/github.com/JostMigenda__;!!OToaGQ!_bJXxXBzgNJTvtkmaRSP2uXvmhPrJjHtMeXc1kTHSyxEFC-8oHCqsEhFUmX0AyPG0w$> Others may feel differently, but I am personally in favor of releasing SNOwGLoBES v. 1.3 without a GEANT4 integration. We're a few user manual revisions away from pushing to public; adding a GEANT4 integration could easily add another year to that timeline (or be a v. 1.4 all by itself). I can definitely see needing that full reconstruction capability, but I agree with you that SNOwGLoBES is not the tool for it.

**Comment by sybenzvi** [comment]
This request for functionality is superseded by `sntools` (and other event generators using `snewpy`) and is obsolete.
