### ISSUE TITLE
`Walk_2019` has outdated version in `model_files.yml`

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#240]
In `model_files.yml`, `Walk_2019` currently lists `release_version: 1.2`. However, those files were updated in #211 which was released as part of v1.3, so we should update the yml file.

More generally, I think this `release_version` property is unnecessary; we always want to use the version of the model files that matches the SNEWPY version. Instead of fixing this one entry manually, we should see whether we can avoid manually specifying the version at all.

_(Thanks to @sgriswol and another IceCube collaborator for discovering this issue!)_

**Comment by sgriswol** [comment]
To clarify our conversation, I only mentioned the `Walk_2019` model, however every model in `model_files.yml` still lists `release_version: 1.2`. This issue was found by loading `Walk_2019` and attempting to interpolate the luminosity/flux. Changes made between SNEWPY v1.3 and v1.2 (#211 ) fixed this issue. 

An implication of this current issue is that, if `model_files.yaml` isn't updated appropriately when changes are made to any model, those changes will be missed when the user attempts to download the models.

**Comment by JostMigenda** [comment]
Quick note that this also affects `Zha_2021` now, see #239.

**Comment by JostMigenda** [comment]
Note that this might be resolved as part of #250.
