### ISSUE TITLE
Documentation for using GLoBES + SNOwGLoBES with snewpy

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#26]
The steps required to manually install GLoBES and SNOwGLoBES and use them with snewpy need to be documented with the project.

This could be a precursor to bundling GLoBES and SNOwGLoBES into the setuptools build. GLoBES could be a challenge due to its reliance on some non-standard libraries like argp.

**Comment by JostMigenda** [comment]
In principle, we have these instructions in the README file. However, I wonder whether we should really keep those here—I think it might be better to refer to SNOwGLoBES’ documentation for that?

Complete instructions for installing SNOwGLoBES should be in their documentation. Duplicating them here doesn’t offer a clear benefit but could potentially cause a lot of confusion if they’re not kept in sync when things change e.g. in a future GLoBES or SNOwGLoBES release, or due to some OS update.

**Comment by sybenzvi** [comment]
Maybe all installation and dependency instructions should be copied from the project README into readthedocs. I would favor keeping the existing detailed instructions since there are some configuration steps that users ought to know about, particularly for GLoBES.

**Comment by JostMigenda** [comment]
Are any of these steps specific to SNEWPY? If so, absolutely, let’s add it to our docs!
For configuration steps that are necessary for any user of GLoBES or SNOwGLoBES, though, those should be explained in the (SNOw)GLoBES documentation and I would avoid duplicating them here.

**Comment by JostMigenda** [comment]
With #193 merged, we don’t depend on GLoBES anymore and instructions for downloading SNOwGLoBES are in the docs; so this issue can now be closed.

> This could be a precursor to bundling GLoBES and SNOwGLoBES into the setuptools build.

Bundling SNOwGLoBES would be nice and should be much easier now that we don’t have to worry about compiling binaries and just need to copy text files on smearing/efficiency/etc. I’ll open a new issue for that.
