### ISSUE TITLE
clean up model notebooks and documentation

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#288]
We are factoring the snewpy repo into code that lives here and model files that live in [snewpy-models-ccsn](https://github.com/SNEWS2/snewpy-models-ccsn). Currently the jupyter notebooks which demonstrate the models live in the folder
```
snewpy/models/{model_name}/{model_name}.ipynb
```
I propose we remove the top-level models folder and copy all the jupyter notebooks into
```
snewpy/doc/nb
```

**Comment by JostMigenda** [comment]
_[Using this issue to follow-up on [this comment in #294](https://github.com/SNEWS2/snewpy/pull/294#pullrequestreview-1908999247)]_

Right now most Jupyter notebooks are only in the `snewpy-models-ccsn` repo. (The exception being notebooks for the recently added `Fornax_2022` and `Mori_2023` models, which are _both_ in `doc/nb/` _and_ in the models repo.)

I don’t have particularly strong feelings on which repo they should go in, but a slight preference for the `snewpy` repo here: Based on experience, changes to SNEWPY occasionally require changes to the sample notebooks, while changes to input files almost never do. Thus, it’s more convenient to keep notebooks here and update them in the same PR, if necessary.

Just one note: I’d prefer something like `doc/nb/ccsn/` (or `doc/nb/presn/`, as appropriate); otherwise, the handful of not model-specific demo notebooks get buried under dozens of model notebooks.
