### ISSUE TITLE
Some issues/things that can be improved

### ISSUE THREAD

**Issue by mcolomermolla** [SNEWS2/snewpy#37]
- For the models, one cannot really choose the input options ntbins and deltat: e.g. delta= 1 gives error
- For snowglobes: I realized that the smeared+weigthed output is null in the case Ar40kt detector

**Comment by evanoconnor** [comment]
Thanks for test driving!

Are you using the main branch or the release-version-1 branch?

**Comment by mcolomermolla** [comment]
I have been using the release-version-1 branch version as when I started using snewpy, there were some bugs in the main branch. I will let you know if I notice something else that can be changed.

By the way, I have been working on modifying from_snowglobes.py so that it provides at output the lightcurves, which are not given in the current form, in a txt with time and number of events. Since I wanted fine bins and it was a bit long, I modified it so that to run it only for three detectors (icecube, 100kt water and 20kt scint), but we can think how to include this implementation properly and I could make a pull request.

**Comment by evanoconnor** [comment]
Thanks. I looked into these two issues.  I can't quite reproduce the ar40kt one.  When I look at the entries in the _smeared_weighted.dat file generated from an argon/ar40kt detector in SNEWPY I see events.  Perhaps I don't quite understand what you mean.

For the other one, using to_snowglobes.generate_time_series(), you either set the number of bins or the dt, since the tmax and tmin are set by the model.  The routine to_snowglobes.generate_fluence() is a little more general.  You can send it an array of tstarts and tends (or single values), it will generate a fluence file for each pair of tstart,tend values.

regarding using fewer detectors, you can use the detect_input="" option to specify just one detector.  I found just looping through my own list is a better way them adding more options in run_snowglobes.

In general, we should try to limit to changes to to_, run_, and from_ snowglobes, since they the core (say private) routines. We should encourage users to do analysis things outside of these routines if possible.  But I understand that some things may need to be in those three files.  

Note, there are some optional arguments to from_snowglobes: skip_plots=False, return_tables=False.  skip_plots=True will make everything _much_ faster.  return_tables=True will give you the data you need to generate the lightcurves as a user and bypass the collated files written out.

**Comment by mcolomermolla** [comment]
For the first point: yes, I know that for to_snowglobes.generate_time_series() you only provide one of them. If I only provide dt different from None, I get this error:
    outfile = to_snowglobes.generate_time_series(models_dir, file_name, modeltype, transformation, parameters, d, output, ntbins, deltat) #runs to_snowglobes
  File "/home/mcolomer/snewpy_clone/snewpy/to_snowglobes.py", line 57, in generate_time_series
    tfname = model_file.replace('.fits', '.' + transformation_type + '.{:.3f},{:.3f},{:d}-{:.1f}'.format(tmin,tmax,ntbins,d) + 'kpc.tar.bz2')
TypeError: unsupported format string passed to NoneType.__format__

For the Ar40kt, strange, I have checked again and it is indeed providing events now...

Thanks for the tips about the rest! 
Indeed, I agree that the analysis should be out of it. It was just about prividing as outut the lightcurve for the analysis actually. But I did not know that actually the return_tables is already providing what is needed.
