### ISSUE TITLE
missing masses and directions for Tamborra 2014, Walk 2018, Walk 2019 models

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#78]
Looking at the Garching models corresponding to Walk 2018/2019 and Tamborra 2014, we are missing directions and progenitor masses. So the models are not complete and we can't simulate anisotropic emission. Do we not have permission to access additional data?

**Comment by sybenzvi** [comment]
> Edit: sorry, ignore me…

To be specific, there are dir1, dir2, dir3 directions mentioned in the papers but we seem to have only dir1, and only some progenitor masses.

**Comment by mcolomermolla** [comment]
For the masses, only two are missing:
- I did not include 11 Msun from Tamborra2014 as it does not show SASI, but it can be done. 
- I did not included 70 Msun because I had not dowloaded the data and used it / done the conversion before for that one, but I can also add it. 

For the directions:
- yes, I only included the most privileged direction for SASI for now, dir 1. I was indeed considering to include the full data with theta and phi in the same way as you implemented the possibility to read these two angles for other models, but I did not do it yet. I also have dir 2 and dir 3 that I can add. 
- For 27 Msun in Tamborra et al I only have these three directions, I did not find the full data with theta and phi in their archive. I will check again.

**Comment by sybenzvi** [comment]
Thanks @mcolomermolla. I'd say add the data you want and then we can figure out the interface later. One easy thing to do from the perspective of the model is to have it take a theta/phi and just return one of the three appropriate directions for that angle.

**Comment by JostMigenda** [comment]
Was just looking through old issues and noticed that this one is still open. PR #231 already added all the missing `Walk_201x` model files; now all that’s missing is directions 2 and 3 for `Tamborra_2014`’s 11.2 and 20 Msol progenitors. Do we still want to add those or can we close this issue?

**Comment by sybenzvi** [comment]
I am adding this to [Hackathon 2024](https://github.com/orgs/SNEWS2/projects/8) so that @mcolomermolla, @JostMigenda, and I are forced to chat about it and make a decision on `Tamborra_2014`. We may just close this without further updates.

**Comment by mcolomermolla** [comment]
I contacted Tamborra to get these diretions, but she replied that they were not stored. That is the reason why I coud not provide them. It is said in the README of the model. This issue can be closed.

**Comment by mcolomermolla** [comment]
I contacted Tamborra to get these diretions, but she replied that they were not stored. That is the reason why I coud not provide them. It is said in the README of the model. This issue can be closed.
